openapi: 3.0.0
servers:
  - url: https://mpt-server.vercel.app/api
    description: Default server
info:
  description: |
    # Introduction
    This API is documented in **OpenAPI format** and is based on
    [Petstore sample](http://petstore.swagger.io/) provided by [swagger.io](http://swagger.io) team.
    It was **extended** to illustrate features of [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo)
    tool and [ReDoc](https://github.com/Redocly/redoc) documentation. In addition to standard
    OpenAPI syntax we use a few [vendor extensions](https://github.com/Redocly/redoc/blob/main/docs/redoc-vendor-extensions.md).

  version: 1.0.0
  title: MPT Server
  contact:
    name: Fareez
    email: mptwaktusolat@gmail.com
    url: https://mpt-server.vercel.app
  x-logo:
    url: "https://imgur.com/umII6oL.png"
    altText: MPT Server banner
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: solat
    description: Prayer time information
  - name: solat v2
    description: Prayer time information (version 2)
  - name: zones
    description: Zones and location information
  - name: mosque
    description: Mosque banner images
  - name: pet_model
    x-displayName: The Pet Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Solat" showReadOnly={true} />
x-tagGroups:
  - name: Prayer times
    tags:
      - solat
      - solat v2
      - zones
      - mosque
  - name: Models
    tags:
      - pet_model
      - store_model
paths:
  /solat:
    get:
      tags:
        - solat
      summary: Prayer time for all zone
      description: Prayer time for all zone for current month
      operationId: getAllPrayerTime
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Solat"
        "405":
          description: Invalid input
  "/solat/{zone}":
    get:
      tags:
        - solat
      summary: Prayer time by zone
      description: Return a list of Solat information for the current month for the given zone
      operationId: getZonePrayerTime
      parameters:
        - name: zone
          in: path
          description: Zone code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Solat"
        "400":
          description: Invalid ID supplied
        "404":
          description: Solat not found
  "/solat/{zone}/{day}":
    get:
      tags:
        - solat
      summary: Prayer time by zone
      description: Return a list of Solat information for the current month in the given day for the given zone
      operationId: getZoneTodayPrayerTime
      parameters:
        - name: zone
          in: path
          description: Zone code
          required: true
          schema:
            type: string
        - name: day
          in: path
          description: Day
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Solat"
        "400":
          description: Invalid ID supplied
        "404":
          description: Solat not found
  "/v2/solat/{zone}":
    get:
      tags:
        - solat v2
      summary: Prayer time by zone
      description: Return a list of Solat information for the current month in the given day for the given zone
      operationId: getPrayerTime
      parameters:
        - name: zone
          in: path
          description: Zone code
          required: true
          schema:
            type: string
        - name: year
          in: query
          required: true
          description: "Year for prayer data. For example: `2023`"
          schema:
            type: integer
        - name: month
          in: query
          description: "Month number (eg: `6` for June). If not given, it will set for the current month"
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SolatV2"
        "400":
          description: Invalid ID supplied
        "404":
          description: Solat not found
  /zones:
    get:
      tags:
        - zones
      summary: All zones
      description: Return all zones information
      operationId: getAllZones
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Zones"
        "405":
          description: Invalid input
  /zones/{zoneCode}:
    get:
      tags:
        - zones
      summary: Zones for the given state
      description: Return zones information for the given zone code only. It is like a filter.
      operationId: getFilteredZones
      parameters:
        - name: zoneCode
          in: path
          description: "Initial zone code. Eg: `prk`, `sgr` etc."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Zones"
        "405":
          description: Invalid input
  /zones/gps:
    get:
      tags:
        - zones
      summary: Get zone by GPS coordinate
      description: Return zone information for the given latitude and longitude
      operationId: getZonesbyGps
      parameters:
        - name: lat
          in: query
          description: "Latitude"
          example: "3.2485"
          required: true
          schema:
            type: string
        - name: lang
          in: query
          description: "Longitude"
          example: "101.739"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimpleZone"
        "405":
          description: Invalid input
  /mosque/{zoneCode}:
    get:
      tags:
        - mosque
      summary: Get mosque image for the given zone
      description: "Return an image URL for the given zone. For example: `sgr` (Selangor) will give you SHAS IIUM Mosque. List for all images are listed [here](/mosques), [here](http://waktusolat.iqfareez.com/mosques)"
      operationId: getMosqueImage
      parameters:
        - name: zoneCode
          in: path
          description: "Initial zone code. Eg: `prk`, `sgr` etc."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            image/*:
              schema:
                type: string
                format: binary

        "405":
          description: Invalid input
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    Solat:
      type: object
      properties:
        prayerTime:
          type: array
          items:
            type: object
            properties:
              hijri:
                type: string
                format: date
                description: Hijri date
                example: "1444-10-10"
              date:
                type: string
                format: string
                description: Gregorian date
                example: "01-May-2023"
              day:
                type: string
                description: Day of the week
                example: "Monday"
              imsak:
                type: string
                format: time
                description: Imsak time
                example: "05:44:00"
              fajr:
                type: string
                format: time
                description: Fajr time
                example: "05:54:00"
              syuruk:
                type: string
                format: time
                description: Syuruk time
                example: "07:02:00"
              dhuhr:
                type: string
                format: time
                description: Dhuhr time
                example: "13:13:00"
              asr:
                type: string
                format: time
                description: Asr time
                example: "16:31:00"
              maghrib:
                type: string
                format: time
                description: Maghrib time
                example: "19:20:00"
              isha:
                type: string
                format: time
                description: Isha time
                example: "20:31:00"
    SolatV2:
      type: object
      properties:
        zone:
          type: string
          example: SGR01
        year:
          type: integer
          example: 2023
        month:
          type: string
          description: Month name
          example: MAY
        last_updated:
          type: string
          format: date-time
          example: "2023-05-18T18:48:11.892Z"
        prayers:
          type: array
          items:
            type: object
            properties:
              hijri:
                type: string
                format: date
                description: Hijri date
                example: "1444-10-10"
              day:
                type: integer
                description: Day number for the month
                example: 2
              fajr:
                type: integer
                format: date-time
                description: Epoch timestamp in seconds
                example: 1682940000
              syuruk:
                type: integer
                format: date-time
                description: Epoch timestamp in seconds
                example: 1682895720
              dhuhr:
                type: integer
                format: date-time
                description: Epoch timestamp in seconds
                example: 1682917980
              asr:
                type: integer
                format: date-time
                description: Epoch timestamp in seconds
                example: 1682891640
              maghrib:
                type: integer
                format: date-time
                description: Epoch timestamp in seconds
                example: 1682944260
              isha:
                type: integer
                format: date-time
                description: Epoch timestamp in seconds
                example: 1682929860
    Zones:
      type: array
      items:
        type: object
        properties: 
          jakimCode:
            type: string
            description: Jakim code
            example: "KDH01"
          negeri:
            type: string
            description: State
            example: "Kedah"
          daerah:
            type: string
            description: District
            example: "Kota Setar, Kubang Pasu, Pokok Sena"
    SimpleZone:
      type: object
      properties:
        state:
          type: string
          description: Negeri
          example: "Pahang"
        state_iso:
          type: string
          description: "State code according to https://data.humdata.org/dataset/geoboundaries-admin-boundaries-for-malaysia/resource/55b3dd6f-5786-4dce-b32f-5eca9bc8c16d"
          example: "MY-06"
        zone:
          type: string
          description: Prayer time zone
          example: "PHG03"
              
